global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: embedded-api
    static_configs:
      - targets: ["api:8000"]

  - job_name: embedded-telemetry-consumer
    static_configs:
      - targets: ["telemetry-consumer:9100"]
